#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: fabric
#   namespace: fabric-network
# spec:
#   storageClassName: rook-cephfs
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 15Gi
